WITH source as (
SELECT 
c.customer_id,
c.company customer_company,
c.last_name customer_last_name,
c.first_name customer_first_name,
c.email_address customer_email_address,
c.job_title customer_job_title,
c.business_phone customer_business_phone,
c.home_phone customer_home_phone,
c.mobile_phone customer_mobile_phone,
c.fax_number customer_fax_number,
c.address customer_address,
c.city customer_city,
c.state_province customer_state_province,
c.zip_postal_code customer_zip_postal_code,
c.country_region customer_country_region,
c.web_page customer_web_page,
c.notes customer_notes,
c.attachments customer_attachments,
e.employee_id,
e.company employee_company,
e.last_name employee_last_name,
e.first_name employee_first_name,
e.email_address employee_email_address,
e.job_title employee_job_title,
e.business_phone employee_business_phone,
e.home_phone employee_home_phone,
e.mobile_phone employee_mobile_phone,
e.fax_number employee_fax_number,
e.address employee_address,
e.city employee_city,
e.state_province employee_state_province,
e.zip_postal_code employee_zip_postal_code,
e.country_region employee_country_region,
e.web_page employee_web_page,
e.notes employee_notes,
e.attachments employee_attachements,
p.product_code,
p.product_name,
p.description,
p.supplier_company,
p.standard_cost,
p.list_price,
p.reorder_level,
p.target_level,
p.quantity_per_unit,
p.discontinued,
p.minimum_reorder_quantity,
p.category,
p.attachments,
po.purchase_order_id,
po.product_id,
po.quantity,
po.unit_cost,
po.date_received,
po.posted_to_inventory,
po.inventory_id,
po.supplier_id,
po.created_by,
po.submitted_date,
po.creation_date,
po.status_id,
po.expected_date,
po.shipping_fee,
po.taxes,
po.payment_date,
po.payment_amount,
po.payment_method,
po.notes,
po.approved_by,
po.approved_date,
po.submitted_by,
current_timestamp() as insertion_timestamp

FROM {{ref('fact_purchase_order')}} po LEFT JOIN {{ref('dim_customer')}} c ON po.customer_id = c.customer_id
LEFT JOIN {{ref('dim_employee')}} e ON po.employee_id = e.employee_id
LEFT JOIN {{ref('dim_products')}} p ON po.product_id = p.product_id
)

SELECT * FROM source